<?php

namespace ASU\StackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WinRepository extends EntityRepository
{
}
