<?php

namespace ASU\StackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StackerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StackerRepository extends EntityRepository {
    
    use \ASU\AssetBundle\Traits\SearchableTrait;

    /**
     * @return array of fields as strings
     */
    public function getSearchableFields() {
        return array(
            'username',
        );
    }

    /**
     * Modifies the search term to suite the field's requirements.
     * 
     * @param string $field
     * @param string $term
     */
    public function normalize($field, $term) {
        switch ($field) {
            case 'username':
                return array($term);
            default:
                return false;
        }
    }
    
}
