<?php

namespace ASU\StackBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StackerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StackerRepository extends EntityRepository {
    
}
