---
- name: Install MySQL Packages
  sudo: yes    
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: Create databases
  sudo: yes
  ignore_errors: yes
  mysql_db: name={{ database_name }} state=present
  with_items: mysql

- name: Create users
  sudo: yes
  ignore_errors: yes
  mysql_user: name={{ database_user }} password={{ database_password }} priv={{ database_name }}.*:ALL state=present
  with_items: mysql