---
    php_ppa: php5-5.6
    doc_root: /vagrant/web
    sys_packages: ["git", "nodejs", "npm"]
    dist: precise
    php_packages: [
        "php5-cli",
        "php5-curl",
        "php5-intl",
        "php5-mcrypt",
        "php5-imagick",
        "php5-xdebug",
        "php5-mysql",
        "supervisor"
    ]
