- name: Install node and npm
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - nodejs
    - npm

- name: link nodejs to node 
  sudo: yes
  command: ln -s /usr/bin/nodejs /usr/bin/node
  args:
    creates: /usr/bin/node
  
- name: install uglify css/js and less
  sudo: yes
  command: npm install -g uglifycss uglify-js less@1.7.5