---
- hosts: all
  sudo: true
  vars:
    web_server: apachephp
    timezone: UTC
    max_nesting_level: 300
    memory_limit: 512M
  vars_files:
    - vars/common.yml
    - [ "vars/apachephp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - apache
    - php5
    - mysql
    - composer
    - phpcommon
    - node
    - app
